apiVersion: v1
kind: Service
metadata:
  name: kubernetesclient-nodeport
  namespace: kubernetesclient-ns
spec:
  type: NodePort
  selector:
    app: kubernetesclient
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 31091
---
apiVersion: apps/v1  #Deployment and StatefulSet is defined in apps/v1 not in corev1
kind: Deployment
metadata:
  name: kubernetesclient   #name of the deployment
  namespace: kubernetesclient-ns
  labels:
    app: kubernetesclient
spec:
  replicas: 1  #for testing purpose i set to 1
  selector:
    matchLabels:
      app: kubernetesclient
  template:
    metadata:
      labels:
        app: kubernetesclient
    spec:
      dnsConfig: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 10    #当删除Pod时，等待时间
      containers:
        - name: kubernetesclient
          image: 127.0.0.1:5000/kubernetesclient-client:1.1.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: port
              containerPort: 8081
          volumeMounts:
            - mountPath: /logs  #directory in docker container
              name: log
          env:
            - name: APP_NAME
              value: "kubernetesclient-server"
            - name: server.port
              value: "8081"
          resources:
            requests:
              memory: "300Mi"
              cpu: "300m"
            limits:
              memory: "300Mi"
              cpu: "300m"
      volumes:
        - name: log
          hostPath:
            path: /home/kubernetesclient-service-k8s/logs  # directory location on host
            type: DirectoryOrCreate